In [8]:
%%bash
# rm -r ../src/__pycache__
# rm ../logs/*
# which python
python --version
tree ..

Python 3.10.12
..
├── LICENSE
├── README.md
├── app.py
├── logs
├── notebooks
│   └── energy-demand-forecasting.ipynb
├── poetry.lock
├── pyproject.toml
├── src
│   ├── __init__.py
│   ├── config.py
│   ├── forecast.py
│   ├── ingest.py
│   ├── logger.py
│   ├── pipeline.py
│   ├── train.py
│   └── transform.py
└── tests
    └── __init__.py

5 directories, 15 files

In [34]:
import glob
import os
import random
import warnings

from pathlib import Path

import numpy as np
import pandas as pd
import plotly.express as px
import psycopg2

from dotenv import load_dotenv
from plotly.graph_objs import Figure
from psycopg2.extensions import connection, cursor
from sqlalchemy import create_engine, Engine

from src.config import Config
from src.ingest import query_data, query_ids
from src.pipeline import ForecastingPipeline
from src.train import get_rsquared

warnings.filterwarnings("ignore")
load_dotenv()

True

In [11]:
# instantiate an object of type, 'ForecastingPipeline'
fp: ForecastingPipeline = ForecastingPipeline(random.choice(query_ids()))

# generate the recursive forecast
forecast: pd.Series = fp.run()

# query the raw data from Postgres
df: pd.DataFrame = query_data(fp.id)

# filter the raw data w.r.t. the recursive forecast's timestamps
df_future: pd.DataFrame = (
    df
    .assign(datetime=pd.to_datetime(df["datetime"]))
    .set_index("datetime")
    .loc[forecast.index]
    .assign(forecast=forecast)
    .rename({"energy_demand": "target"}, axis=1)
)

# evaluate the forecast
naive_forecast: float = fp.stationary_data.iloc[-1]["energy_demand"]
baseline_forecast: float = df_future.target.mean()
naive_rmse: float = np.sqrt(np.mean((df_future.target.values - naive_forecast)**2))
baseline_rmse: float = np.sqrt(np.mean((df_future.target.values - baseline_forecast)**2))
forecast_rmse: float = np.sqrt(np.mean((df_future.target.values - df_future.forecast.values)**2)) 
print(
    f"Naive RMSE: {naive_rmse:.2f}\
    \nBaseline RMSE: {baseline_rmse:.2f}\
    \nForecast RMSE: {forecast_rmse:.2f}\
    \nR²: {get_rsquared(df_future.target, df_future.forecast):.2f}"
)

# plot the out-of-sample target and recursive forecast 
fig: Figure = px.line(
    df_future,
    x=df_future.index, 
    y=["target", "forecast"], 
    color_discrete_map={"target": "green", "forecast": "red"},
    labels={"index": "Datetime", "value": "Energy Demand (MW)", "variable": ""},
    template="plotly_dark", 
    markers=True, 
    title=f"{fp.id.upper()} Hourly Energy Demand"
)
fig.show()

100%|██████████| 20/20 [00:08<00:00,  2.24trial/s, best loss: 0.008227485951497582]
Naive RMSE: 519.74
Baseline RMSE: 518.18
Forecast RMSE: 79.41
R²: 0.98

##### **Creating and writing to PostgreSQL's *`time_series.energy_demand`* table**

In [9]:
paths: list[str] = glob.glob(os.path.join(Config.Path.HOME_DIR / "raw_data", "*.csv"))
dataset_ids: list[str] = [Path(path).stem.split("_")[0].lower() for path in paths]
display(paths, dataset_ids)

['/Users/ncheymbamalu/Desktop/PersonalProjects/energy-demand-forecasting/raw_data/PJMW_hourly.csv',
 '/Users/ncheymbamalu/Desktop/PersonalProjects/energy-demand-forecasting/raw_data/DAYTON_hourly.csv',
 '/Users/ncheymbamalu/Desktop/PersonalProjects/energy-demand-forecasting/raw_data/NI_hourly.csv',
 '/Users/ncheymbamalu/Desktop/PersonalProjects/energy-demand-forecasting/raw_data/PJME_hourly.csv',
 '/Users/ncheymbamalu/Desktop/PersonalProjects/energy-demand-forecasting/raw_data/FE_hourly.csv',
 '/Users/ncheymbamalu/Desktop/PersonalProjects/energy-demand-forecasting/raw_data/DOM_hourly.csv',
 '/Users/ncheymbamalu/Desktop/PersonalProjects/energy-demand-forecasting/raw_data/EKPC_hourly.csv',
 '/Users/ncheymbamalu/Desktop/PersonalProjects/energy-demand-forecasting/raw_data/DEOK_hourly.csv',
 '/Users/ncheymbamalu/Desktop/PersonalProjects/energy-demand-forecasting/raw_data/DUQ_hourly.csv',
 '/Users/ncheymbamalu/Desktop/PersonalProjects/energy-demand-forecasting/raw_data/AEP_hourly.csv',
 '/Users/ncheymbamalu/Desktop/PersonalProjects/energy-demand-forecasting/raw_data/COMED_hourly.csv']

['pjmw',
 'dayton',
 'ni',
 'pjme',
 'fe',
 'dom',
 'ekpc',
 'deok',
 'duq',
 'aep',
 'comed']

In [10]:
dfs: list[pd.DataFrame] = [
    (
        pd.read_csv(path)
        .rename(
            dict(zip(pd.read_csv(path).columns.tolist(), ["datetime", "values"])),
            axis=1
        )
        .assign(id=dataset_id)
    )
    for path, dataset_id in zip(paths, dataset_ids)
]
df: pd.DataFrame = pd.concat(dfs, axis=0, ignore_index=True)

In [11]:
display(df.shape)
df.sample(5).sort_index()

(1057271, 3)

                   datetime   values    id
120041  2015-01-21 19:00:00   7350.0  pjmw
325471  2002-09-17 22:00:00  35016.0  pjme
628492  2016-07-26 19:00:00  18422.0   dom
821222  2013-12-03 07:00:00   1638.0   duq
844227  2015-04-19 21:00:00   1334.0   duq

In [12]:
HOST: str | None = os.getenv("HOST")
DB: str | None = os.getenv("DB")
USER: str | None = os.getenv("USER")
PWD: str | None = os.getenv("PASSWORD")
PORT: str | None = os.getenv("PORT")

In [7]:
# create the psycopg2 'connection' and 'cursor' objects
conn: connection = psycopg2.connect(
    host=HOST,
    dbname=DB,
    user=USER,
    password=PWD,
    port=int(PORT)
)
cur: cursor = conn.cursor()

In [14]:
# create the query which will be used to create the 'time_series.energy_demand' table
schema: str = "time_series"
table: str = "energy_demand"
QUERY: str = f"""CREATE SCHEMA IF NOT EXISTS {schema};
CREATE TABLE IF NOT EXISTS {schema}.{table} (
    datetime varchar(25),
    values float,
    id varchar(10)
);
"""
print(QUERY)

CREATE SCHEMA IF NOT EXISTS time_series;
CREATE TABLE IF NOT EXISTS time_series.energy_demand (
    datetime varchar(25),
    values float,
    id varchar(10)
);

In [9]:
# create the 'time_series.energy_demand' table in PostgreSQL
cur.execute(QUERY)
conn.commit()
cur.close()
conn.close()

In [19]:
# creat the sqlalchemy 'Engine' object, which will be used to ...
# write the 'df' pd.DataFrame to the 'time_series.energy_demand' table
engine: Engine = create_engine(f"postgresql://{USER}:{PWD}@{HOST}:{PORT}/{DB}")

# write the 'df' pd.DataFrame to the 'time_series.energy_demand' table
df.to_sql(schema=schema, name=table, con=engine, if_exists="append", index=False)

271

#### **`Alternative way of reading a SQL database table in as a pd.DataFrame`**

In [14]:
engine: Engine = create_engine(f"postgresql://{USER}:{PWD}@{HOST}:{PORT}/{DB}")

In [31]:
# alternative way of querying a SQL database using the Pandas 'read_sql_query' method
query: str = """
SELECT
    distinct id
FROM
    time_series.energy_demand
"""
ids: list[str] = pd.read_sql_query(query, engine.connect()).squeeze().tolist()
ids

['aep',
 'comed',
 'dayton',
 'deok',
 'dom',
 'duq',
 'ekpc',
 'fe',
 'ni',
 'pjme',
 'pjmw']

In [35]:
# alternative way of querying a SQL database using the Pandas 'read_sql_query' method
query: str = f"""
SELECT
    datetime,
    values as energy_demand_mw
FROM
    time_series.energy_demand
WHERE
    "id" = '{random.choice(ids)}'
"""
(
    pd.read_sql_query(query, engine.connect(), parse_dates="datetime")
    .drop_duplicates(subset="datetime")
    .set_index("datetime")
    .asfreq(freq="H")
)

                     energy_demand_mw
datetime
2004-10-01 01:00:00            1621.0
2004-10-01 02:00:00            1536.0
2004-10-01 03:00:00            1500.0
2004-10-01 04:00:00            1434.0
2004-10-01 05:00:00            1489.0
...                               ...
2018-08-02 20:00:00            2554.0
2018-08-02 21:00:00            2481.0
2018-08-02 22:00:00            2405.0
2018-08-02 23:00:00            2250.0
2018-08-03 00:00:00            2042.0

[121296 rows x 1 columns]